nodeLinker: node-modules

# Disable PnP to avoid ESM issues with Vite
pnpMode: loose

# Enable better compatibility
enableGlobalCache: true
enableTelemetry: false

# Package extensions
packageExtensions:
  "@vitejs/plugin-react@*":
    dependencies:
      "@types/babel__core": "*"
